language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "pypy"

env:
  - GEVENT=true
  - GEVENT=false

install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install --upgrade pytest python-coveralls coverage pytest-cov pytest-timeout
  - travis_retry pip install -r requirements.txt
  - echo TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION}
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} != "3" ]; then travis_retry pip install contextlib2; fi
  - if [ "$GEVENT" = "true" ]; then travis_retry pip install gevent; fi
  - python setup.py --version

# Run test
script:
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then py.test --cov=pystorm --cov-config .coveragerc --timeout=10; fi
  - if [ $TRAVIS_PYTHON_VERSION != "3.6" ]; then py.test --timeout=10; fi

# Calculate coverage on success
after_success:
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then coveralls --config_file .coveragerc; fi
